language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
cache: npm
before_script:
- npm run build
- npm run lint
jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '8'
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      skip_cleanup: true
      email: npm@zillessen.info
      api_key:
        secure: wMQ11jcB9+5t/vKBWzo2zsR7UkLbE8+v0hFPPlgJcD+VDz4RlbK0aGHRqINh8vgUWvJMQCJzfcHevnvoZ/EqMQqtuSZE+0lrQ5ro3be9Ily5ymmfYT58EoggPkhufALqYi9rSfahsijiSHB72enORaytPy9KLGLgh6hiKfiCuI5jfOIPtr+tntYljAF6MkF/vJsXU584jjC5TLJXYM2HUBIghNduyq5361JXD/HITB5LV04Rc0zZrH/8wNO6+sej8wjnxwfxwEFFYqjjnGFHd9qTCJYWBVFRVn71L6rJpgo3Rn9H+pyw0X/o1ackAxsFdm6IzDFjN9eZVAoPeHuyTHt/wjZS/UGonKLq17cPmCDtT/d+LBTF1EmxOGsQLWp8b7P5H7BomUwxE5V9M/WiATTzITyhYFi0VP76ARps19ksSjotnY2qvcVTWMYMULfE0tgDXYQFmRi8+cJqJ7aQ/2e3yzvBFlcj9REZWTRMPeExC1PV5xjwx6R+NCd7qvrAqkreIkO0GSe0TEHjUle7DfowH4LSceW1KZEG3J/tITwty4KM59tGDc1xhMNQgJa+PNzAV3U3WKZxClOExTwUsRRdgKCehvnEksfDFEzoDlSBDXGNm2x1CoOzmYSd2fGJ863XDIhTCPKF+ZgjQnTYAKNhUaRbhcPUSqWkWY0AJzY=
      on:
        tags: true
        repo: sebastianzillessen/ngx-translate-extract
